services:
  tomcat:
    build:
      context: ./tomcat
    ports:
      - 8013:8080
    depends_on:
      - mysql  # 等待数据库服务启动
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    ports:
      - 3307:3306
    networks:
      - app-network
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
